spring:
  application:
    name: discoveryserver

server:
  port: 8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

  instance:
    hostname: localhost
