package com.etiyacrm.customerservice.outservices.mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: F17C27A5423B78425C70A70706EFDEB56DC8E3C99D2638D5BBEACBA80B5895948A78718C0120E0982AFDAB0F654504553DB24F86CD2FC2F4F970AEA9EE9CB5D1
//------------------------------------------------------------------------
import java.util.Date;


public interface LWPDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}